### DISCUSSION TITLE
Got error when pull docker image Netatalk 4

### DISCUSSION THREAD

**Discussion by libtantang** [Netatalk/netatalk#1662] [Q&A] [answered]
I am using netatalk 3 through docker compose for several months.When i try to pull netatalk 4 through docker compose, just got the error messages below:

Error response from daemon: pull access denied for netatalk, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Is there something wrong?

Thanks in advance.

**Comment by rdmark** [comment]
That's unexpected. I just tried `docker pull netatalk/netatalk:latest` from one of my machines and was able to pull the image successfully.

Are you using a different method than the above to pull it?

**Comment by libtantang** [comment]
Thanks for your reply.

`docker pull netatalk/netatalk:latest`  works ,but if use [docker-compose.yml ](https://github.com/Netatalk/netatalk/blob/main/docker-compose.yml),it just got error message  i just post.

Maybe something wrong in docker-compose.yml?

**Reply by rdmark** [reply]
Would you mind sharing the contents of your docker-compose.yml file?

**Comment by libtantang** [comment]
Thanks for you time,this is my docker-compose.yml

```
services:
  netatalk:
    image: netatalk:latest
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - /media/xxx/afpshare:/mnt/afpshare
      - /media/xxx/afpbackup:/mnt/afpbackup
      - /var/run/dbus:/var/run/dbus  
    environment:
      - AFP_USER=xxx
      - AFP_PASS=xxx
      - AFP_GROUP=afpusers
      - ATALKD_INTERFACE=
      - TZ=
volumes:
  afpshare:
  afpbackup:
```
