### ISSUE TITLE
I can't backup after updating to 3.2

### ISSUE THREAD

**Issue by marcosvrs** [Netatalk/netatalk#1068]
**Describe the bug**
I can't backup after updating to 3.2.
It says, "Verification may have been interrupted by a network problem. Try again after the network problems are resolved."
<img width="262" alt="Screenshot 2024-06-04 at 16 53 33" src="https://github.com/Netatalk/netatalk/assets/10147574/521ac4c0-d824-446c-804a-de66c3d33233">

Just tested with 3.1.18 and it works with the same settings.

**To Reproduce**
```yaml
  netatalk:
    image: netatalk/netatalk3
    environment:
      AFP_PASS: [secret]
      AFP_USER: marcosvr
      LANG: C.UTF-8
    cap_add:
      - NET_ADMIN
    network_mode: host
    volumes:
      - /mnt/afpbackup:/mnt/afpbackup
      - /var/run/dbus:/var/run/dbus
```

**Expected behavior**
It should work as version 3.1.18.

**Environment**
 - Server OS: Ubuntu 24.04
 - Client OS: macOS Sonoma 14.5
 - Netatalk Version: 3.2

**Logs**
https://pastebin.com/XHUZU1cY
